Test app request

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -65,3 +65,13 @@ jobs:
 
       - name: Fetch Docker container logs
         run: docker logs k2r-spring-boot-app
+
+      - name: Test Spring Application
+        run: |
+          response=$(curl --write-out "%{http_code}" --silent --output /dev/null http://k2r-spring-boot-app:8080/api/company/list)
+          if [ "$response" -ne 200 ]; then
+            echo "Application failed to start or returned non-200 status code: $response"
+            exit 1
+          else
+            echo "Application started successfully with response code: $response"
+          fi
